language: node_js
node_js:
  - "stable"
install:
  - npm install -g firebase-tools
script:
  - echo "deploying"
after_successs:
  - firebase deploy --token $FIREBASE_TOKEN
# 1/b5aKx8NmuqLIdFhNrksOgjGuLcs_Nvrj-v6S6AbdXVNyAeN_25vHpqeR49CkMmmS
